import {Dish} from './dishes/dish/dish.component';

export const dishes: Dish[] = [
        {
            "name": "dish1",
            "country": "Poland",
            "category": "seafood",
            "ingredients": ["ing1","ing2"],
            "maxNo": 4,
            "price": 12,
            "description": "super",
            "photos": ["img1", "img2", "img3"],
            "show": true,
            "votes": 0,
            "rating": 0
        },
        {
            "name": "dish2",
            "country": "Poland",
            "category": "regional",
            "ingredients": ["ing3","ing5"],
            "maxNo": 12,
            "price": 8,
            "description": "tradycyjne jedzenie",
            "photos": ["img1", "img2", "img3"],
            "show": true,
            "votes": 0,
            "rating": 0
        },
        {
            "name": "dish3",
            "country": "Norway",
            "category": "dessert",
            "ingredients": ["ing1", "ing3", "ing5"],
            "maxNo": 2,
            "price": 9,
            "description": "deser norweski",
            "photos": ["img1", "img2", "img3"],
            "show": true,
            "votes": 0,
            "rating": 0
        },
        {
            "name": "dish4",
            "country": "Ukraine",
            "category": "soup",
            "ingredients": ["ing2", "ing3"],
            "maxNo": 3,
            "price": 2,
            "description": "ukrainskie jedzenie",
            "photos": ["img1", "img2", "img3"],
            "show": true,
            "votes": 0,
            "rating": 0 
        },
        {
            "name": "dish5",
            "country": "Slovakia",
            "category": "seafood",
            "ingredients": ["ing1","ing2"],
            "maxNo": 42,
            "price": 8,
            "description": "super",
            "photos": ["img1", "img2", "img3"],
            "show": true,
            "votes": 0,
            "rating": 0 
        },
        {
            "name": "dish6",
            "country": "China",
            "category": "seafood",
            "ingredients": ["ing1", "ing2"],
            "maxNo": 20,
            "price": 38,
            "description": "super chinskie jedzenie",
            "photos": ["img1", "img2", "img3"],
            "show": true,
            "votes": 0,
            "rating": 0 
        },
        {
            "name": "dish7",
            "country": "Vietnam",
            "category": "regional",
            "ingredients": ["ing1", "ing2"],
            "maxNo": 426,
            "price": 23,
            "description": "wietnamskie",
            "photos": ["img1", "img2", "img3"],
            "show": true,
            "votes": 0,
            "rating": 0 
        },
        {
            "name": "dish8",
            "country": "Poland",
            "category": "dessert",
            "ingredients": ["ing1","ing4"],
            "maxNo": 12,
            "price": 11,
            "description": "super",
            "photos": ["img1", "img2", "img3"],
            "show": true,
            "votes": 0,
            "rating": 0 
        },
        {
            "name": "dish9",
            "country": "Austria",
            "category": "dessert",
            "ingredients": ["ing1", "ing2"],
            "maxNo": 41,
            "price": 15,
            "description": "super",
            "photos": ["img1", "img2", "img3"],
            "show": true,
            "votes": 0,
            "rating": 0 
        },
        {
            "name": "dish10",
            "country": "Italy",
            "category": "seafood",
            "ingredients": ["ing1", "ing2"],
            "maxNo": 41,
            "price": 12,
            "description": "super",
            "photos": ["img1", "img2", "img3"],
            "show": true,
            "votes": 0,
            "rating": 0 
        },
        {
            "name": "dish11",
            "country": "Sweden",
            "category": "seafood",
            "ingredients": ["ing1", "ing2"],
            "maxNo": 14,
            "price": 12,
            "description": "super",
            "photos": ["img1", "img2", "img3"],
            "show": true,
            "votes": 0,
            "rating": 0 
        },
        {
            "name": "dish12",
            "country": "Norway",
            "category": "seafood",
            "ingredients": ["ing1", "ing2"],
            "maxNo": 46,
            "price": 18,
            "description": "super",
            "photos": ["img1", "img2", "img3"],
            "show": true,
            "votes": 0,
            "rating": 0 
        }
    ]